name: Staging

on: pull_request

permissions:
  contents: read
  packages: write

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'
            - name: Update pip
              run: python -m pip install --upgrade pip
            - name: Install dependencies
              run: pip install -r requirements.txt
            - name: Inspect
              run: ls -l && ls -l content
            - name: Build site
              run: syrinx . -c -e staging
            - name: Inspect files
              run: ls -l dist/
            - name: Log in to the Container registry
              uses: docker/login-action@v3.3.0
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v6.10.0
              with:
                file: Dockerfile
                no-cache: true
                push: true
                tags: ghcr.io/eegmanylabs/eegmanylabsorg:latest
            - name: Deploy the app
              uses: digitalocean/app_action/deploy@v2
              env:
                IMAGE_DIGEST: ${{ steps.push.outputs.digest }}
                GHCR_CREDS: ${{ secrets.GHCR_CREDS }}
              with:
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
                app_spec_location: .do/eegmanylabs-dev.yml
                print_build_logs: true
                print_deploy_logs: true